version: '3.3'

networks:
 web:
  external: true
   
services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: always
        ports:
        - 80:80
        - 443:443
        expose:
        - 8080
        networks:
        - web
        labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=web"
        - "traefik.basic.frontend.rule=Host:${TRAEFIK_DOMAIN}"
        - "traefik.frontend.auth.basic.users=${TRAEFIK_PW}"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik-config:/etc/traefik/
        command: --docker --api --logLevel=INFO