[entryPoints]
    [entryPoints.http]
    address = ":80"

[api]
	entryPoint = "traefik"
	dashboard=true

[ping]

[docker]
	watch = true

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]
